version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  userbot:
    build:
      context: .
      dockerfile: docker/Dockerfile.userbot
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
